import { Destination } from './types';

export const DESTINATIONS: Destination[] = [
  {
    id: '1',
    name: 'Candi Borobudur',
    location: 'Magelang, Jawa Tengah',
    description: 'Candi Budha terbesar di dunia, sebuah mahakarya arsitektur kuno yang menakjubkan.',
    price: 3500000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?q=80&w=2071&auto=format&fit=crop',
    tags: ['Budaya', 'Sejarah', 'Edukasi'],
    matchScore: 95,
    facilities: ['Wi-Fi', 'Pemandu Wisata', 'Area Parkir', 'Toilet'],
    culture: 'Warisan Budaya Buddha tertua di dunia dengan arsitektur Javanese-Buddhist yang megah.',
    food: ['Gudeg Magelang', 'Bakpia Pathok', 'Sego Megono'],
    language: 'Bahasa Jawa & Indonesia',
    coordinates: { lat: -7.607, lng: 110.203 }
  },
  {
    id: '2',
    name: 'Raja Ampat',
    location: 'Papua Barat',
    description: 'Surga bawah laut dengan keanekaragaman hayati laut tertinggi di dunia.',
    price: 15000000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1516690553959-71a414d6b9b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Bahari', 'Petualangan', 'Eksotis'],
    matchScore: 92,
    facilities: ['Diving Center', 'Resort', 'Perahu Wisata'],
    culture: 'Kesenian ukir kayu suku Asmat dan musik petikan tradisional Papua yang khas.',
    food: ['Papeda', 'Ikan Kuah Kuning', 'Sagu Sep'],
    language: 'Bahasa Papua & Indonesia',
    coordinates: { lat: -0.231, lng: 130.518 }
  },
  {
    id: '3',
    name: 'Taman Nasional Komodo',
    location: 'NTT',
    description: 'Rumah bagi kadal purba Komodo dan pemandangan pulau Padar yang spektakuler.',
    price: 8500000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=2070&auto=format&fit=crop',
    tags: ['Alam', 'Satwa', 'Hiking'],
    matchScore: 90,
    facilities: ['Pemandu Wisata', 'Kantin', 'Toilet'],
    culture: 'Kultur masyarakat pesisir Manggarai yang hidup berdampingan dengan alam liar.',
    food: ['Seafood Bakar', 'Kopi Flores', 'Jagung Bose'],
    language: 'Bahasa Manggarai & NTT',
    coordinates: { lat: -8.583, lng: 119.5 }
  },
  {
    id: '4',
    name: 'Gunung Bromo',
    location: 'Probolinggo, Jawa Timur',
    description: 'Pemandangan matahari terbit yang ikonik dengan latar belakang kawah Bromo yang mengepul.',
    price: 2500000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1602641021461-12503957eb6a?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pegunungan', 'Fotografi', 'Petualangan'],
    matchScore: 88,
    facilities: ['Jeep Sewa', 'Kuda', 'Toilet', 'Warung Makan'],
    culture: 'Upacara Kasada dari Suku Tengger yang memuja Dewa di kawah Bromo.',
    food: ['Bakso Malang', 'Nasi Campur Bromo', 'Jagung Bakar'],
    language: 'Bahasa Jawa Tengger',
    coordinates: { lat: -7.942, lng: 112.953 }
  },
  {
    id: '5',
    name: 'Danau Toba',
    location: 'Parapat, Sumatera Utara',
    description: 'Danau vulkanik terbesar di dunia dengan keindahan Pulau Samosir di tengahnya.',
    price: 4000000,
    distance: 0,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1544526226-d4568090ffb8?q=80&w=2070&auto=format&fit=crop',
    tags: ['Danau', 'Budaya', 'Keluarga'],
    matchScore: 85,
    facilities: ['Kapal Wisata', 'Hotel', 'Restoran'],
    culture: 'Rumah adat Bolon dan pertunjukan boneka Sigale-gale khas suku Batak Toba.',
    food: ['Arsik Ikan Mas', 'Mie Gomak', 'Dali ni Horbo'],
    language: 'Bahasa Batak Toba',
    coordinates: { lat: 2.684, lng: 98.847 }
  },
  {
    id: '6',
    name: 'Tanah Lot',
    location: 'Tabanan, Bali',
    description: 'Pura yang terletak di atas batu karang besar di pinggir laut, sangat indah saat matahari terbenam.',
    price: 3000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=2076&auto=format&fit=crop',
    tags: ['Pura', 'Pantai', 'Religi'],
    matchScore: 87,
    facilities: ['Area Parkir', 'Toko Suvenir', 'Toilet'],
    culture: 'Tradisi Odalan dan ritual sembahyang harian umat Hindu Bali di tepi samudra.',
    food: ['Ayam Betutu', 'Sate Lilit', 'Babi Guling'],
    language: 'Bahasa Bali & Indonesia',
    coordinates: { lat: -8.621, lng: 115.086 }
  },
  {
    id: '7',
    name: 'Wakatobi',
    location: 'Sulawesi Tenggara',
    description: 'Destinasi diving kelas dunia dengan terumbu karang yang masih sangat alami.',
    price: 12000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=2070&auto=format&fit=crop',
    tags: ['Bahari', 'Diving', 'Relaksasi'],
    matchScore: 84,
    facilities: ['Diving Boat', 'Resort', 'Wi-Fi'],
    culture: 'Kehidupan suku Bajo, para pengembara laut yang legendaris di Nusantara.',
    food: ['Kasami', 'Sinonggi', 'Lapa-lapa'],
    language: 'Bahasa Wakatobi & Bajo',
    coordinates: { lat: -5.603, lng: 123.63 }
  },
  {
    id: '8',
    name: 'Labuan Bajo',
    location: 'Manggarai Barat, NTT',
    description: 'Gerbang utama menuju Pulau Komodo dengan pelabuhan yang sangat menawan.',
    price: 9000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Sailing', 'Gourmet'],
    matchScore: 89,
    facilities: ['Kapal Phinisi', 'Bandara Internasional', 'Hotel Mewah'],
    culture: 'Perpaduan budaya maritim dan pegunungan Manggarai di Barat Flores.',
    food: ['Seafood Platter', 'Kopi Juria', 'Ikan Cara'],
    language: 'Bahasa Manggarai',
    coordinates: { lat: -8.490, lng: 119.880 }
  },
  {
    id: '9',
    name: 'Kepulauan Derawan',
    location: 'Berau, Kalimantan Timur',
    description: 'Berhenti untuk melihat penyu bertelur dan berenang bersama ubur-ubur tanpa sengat.',
    price: 7000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?q=80&w=1974&auto=format&fit=crop',
    tags: ['Penyu', 'Bahari', 'Ubur-ubur'],
    matchScore: 83,
    facilities: ['Homestay', 'Alat Snorkeling', 'Pemandu Lokal'],
    culture: 'Kultur pesisir Kalimantan yang sangat bergantung pada kelestarian penyu.',
    food: ['Tehe-tehe', 'Elai', 'Seafood Segar'],
    language: 'Bahasa Melayu Berau',
    coordinates: { lat: 2.285, lng: 118.238 }
  },
  {
    id: '10',
    name: 'Bunaken',
    location: 'Manado, Sulawesi Utara',
    description: 'Taman laut yang terkenal dengan dinding karang (wall diving) yang spektakuler.',
    price: 6000000,
    distance: 0,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1629236467006-25807490076c?q=80&w=2070&auto=format&fit=crop',
    tags: ['Bahari', 'Snorkeling', 'Wall Diving'],
    matchScore: 81,
    facilities: ['Sewa Alat Selam', 'Transportasi Perahu', 'Warung Makan'],
    culture: 'Kultur Minahasa yang kaya akan sejarah perdagangan rempah dan musik Kolintang.',
    food: ['Bubur Manado', 'Cakalang Fufu', 'Klappertaart'],
    language: 'Bahasa Manado',
    coordinates: { lat: 1.616, lng: 124.757 }
  },
  {
    id: '11',
    name: 'Nusa Penida',
    location: 'Klungkung, Bali',
    description: 'Pulau eksotis dengan tebing ikonik Kelingking Beach dan air laut yang biru kristal.',
    price: 4500000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Tebing', 'Instagenic'],
    matchScore: 94,
    facilities: ['Penyewaan Motor', 'Tour Lokal', 'Restoran'],
    culture: 'Tradisi spiritual Bali yang sangat kuat dengan banyak pura suci di dinding tebing.',
    food: ['Ikan Bakar', 'Tipat Cantok', 'Sate Renteng'],
    language: 'Bahasa Bali Alus',
    coordinates: { lat: -8.728, lng: 115.544 }
  },
  {
    id: '12',
    name: 'Gili Trawangan',
    location: 'Lombok, NTB',
    description: 'Pulau bebas kendaraan bermotor dengan suasana pesta yang hidup dan snorkeling yang indah.',
    price: 5500000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1534008757030-27299c4371b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Nightlife', 'Snorkeling'],
    matchScore: 91,
    facilities: ['Sewa Sepeda', 'Cidomo', 'Bar Tepi Pantai'],
    culture: 'Perpaduan budaya Sasak lokal dengan komunitas traveler global yang santai.',
    food: ['Ayam Taliwang', 'Plecing Kangkung', 'Sate Rembiga'],
    language: 'Bahasa Sasak & Inggris',
    coordinates: { lat: -8.351, lng: 116.039 }
  },
  {
    id: '13',
    name: 'Gunung Rinjani',
    location: 'Lombok, NTB',
    description: 'Gunung berapi tertinggi kedua di Indonesia dengan Danau Segara Anak yang memukau.',
    price: 6500000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1554486855-33ec7c81604a?q=80&w=2070&auto=format&fit=crop',
    tags: ['Mendaki', 'Alam', 'Danau'],
    matchScore: 88,
    facilities: ['Pemandu Gunung', 'Camping Gear', 'Porter'],
    culture: 'Mitos Dewi Anjani yang sakral bagi masyarakat Lombok dan pendaki.',
    food: ['Ayam Taliwang', 'Sate Bulayak', 'Nasi Balap Puyung'],
    language: 'Bahasa Sasak',
    coordinates: { lat: -8.411, lng: 116.457 }
  },
  {
    id: '14',
    name: 'Dataran Tinggi Dieng',
    location: 'Wonosobo, Jawa Tengah',
    description: 'Negeri di atas awan dengan keindahan candi kuno, kawah belerang, dan Danau Warna.',
    price: 3000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1627914022830-745a3375b47a?q=80&w=2070&auto=format&fit=crop',
    tags: ['Budaya', 'Dingin', 'Alam'],
    matchScore: 86,
    facilities: ['Homestay', 'Area Parkir', 'Warung Kopi'],
    culture: 'Fenomena bocah rambut gimbal dan upacara pemotongan rambut di Dieng Culture Festival.',
    food: ['Mie Ongklok', 'Carica', 'Kripik Jamur'],
    language: 'Bahasa Jawa Ngoko',
    coordinates: { lat: -7.218, lng: 109.916 }
  },
  {
    id: '15',
    name: 'Pulau Belitung',
    location: 'Bangka Belitung',
    description: 'Pantai dengan formasi batu granit raksasa yang artistik dan air yang sangat jernih.',
    price: 5000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Geopark', 'Fotografi'],
    matchScore: 89,
    facilities: ['Sewa Perahu', 'Hotel', 'Seafood'],
    culture: 'Budaya literasi Laskar Pelangi dan sejarah tambang timah yang bersejarah.',
    food: ['Mie Belitung', 'Kopi Joss', 'Gangan Ikan'],
    language: 'Bahasa Melayu Belitung',
    coordinates: { lat: -2.741, lng: 107.618 }
  },
  {
    id: '16',
    name: 'Tana Toraja',
    location: 'Toraja, Sulawesi Selatan',
    description: 'Warisan budaya unik dengan rumah adat Tongkonan dan tradisi pemakaman tebing.',
    price: 7000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=2094&auto=format&fit=crop',
    tags: ['Budaya', 'Sejarah', 'Antropologi'],
    matchScore: 84,
    facilities: ['Pemandu Adat', 'Hotel Lokal', 'Transportasi'],
    culture: 'Ritual Rambu Solo, perayaan kematian paling spektakuler di dunia dengan pengorbanan kerbau.',
    food: ['Pa\'piong', 'Kopi Toraja', 'Jammala'],
    language: 'Bahasa Toraja',
    coordinates: { lat: -2.981, lng: 119.897 }
  },
  {
    id: '17',
    name: 'Tanjung Puting',
    location: 'Kotawaringin Barat, Kalimantan Tengah',
    description: 'Pusat rehabilitasi orangutan di ekosistem hutan hujan tropis yang asri.',
    price: 9500000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1518384400537-88f61a15320d?q=80&w=2070&auto=format&fit=crop',
    tags: ['Satwa', 'Sungai', 'Edukasi'],
    matchScore: 87,
    facilities: ['Kapal Klotok', 'Koki Kapal', 'Pemandu Liar'],
    culture: 'Budaya sungai suku Dayak dan konservasi orangutan di jantung Kalimantan.',
    food: ['Wadi Ikan', 'Juhu Singkah', 'Soto Banjar'],
    language: 'Bahasa Dayak & Banjar',
    coordinates: { lat: -2.859, lng: 111.902 }
  },
  {
    id: '18',
    name: 'Kepulauan Karimunjawa',
    location: 'Jepara, Jawa Tengah',
    description: 'Gugusan pulau dengan penangkaran hiu dan spot snorkeling terumbu karang yang cantik.',
    price: 4000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=2076&auto=format&fit=crop',
    tags: ['Bahari', 'Relaksasi', 'Hiu'],
    matchScore: 85,
    facilities: ['Ferry Cepat', 'Homestay', 'Alat Snorkeling'],
    culture: 'Kultur masyarakat nelayan Jawa yang damai dengan tradisi pembuatan kapal kayu.',
    food: ['Pindang Serani', 'Tahu Bakso', 'Ikan Bakar Pesisir'],
    language: 'Bahasa Jawa Pesisir',
    coordinates: { lat: -5.857, lng: 110.439 }
  },
  {
    id: '19',
    name: 'Kawah Ijen',
    location: 'Banyuwangi, Jawa Timur',
    description: 'Fenomena api biru (Blue Fire) yang langka dan kawah asam terbesar di dunia.',
    price: 3500000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1549420546-24e03ce6df97?q=80&w=2073&auto=format&fit=crop',
    tags: ['Gunung', 'Belerang', 'Mendaki'],
    matchScore: 88,
    facilities: ['Masker Gas', 'Ojek Troli', 'Warung'],
    culture: 'Kehidupan keras penambang belerang dan tradisi Gandrung dari suku Osing.',
    food: ['Nasi Tempong', 'Pecel Pitik', 'Rujak Soto'],
    language: 'Bahasa Jawa Osing',
    coordinates: { lat: -8.058, lng: 114.242 }
  },
  {
    id: '20',
    name: 'Pantai Ora',
    location: 'Maluku Tengah',
    description: 'Maladewa-nya Indonesia dengan resort terapung di atas air laut yang bening seperti kaca.',
    price: 11000000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=2070&auto=format&fit=crop',
    tags: ['Eksotis', 'Bulan Madu', 'Bahari'],
    matchScore: 93,
    facilities: ['Resort Terapung', 'Restoran', 'Tour Kano'],
    culture: 'Musik Tifa dan keramahan suku Alifuru di pulau Seram yang eksotis.',
    food: ['Papeda', 'Sagu Kasbi', 'Rujak Natsepa'],
    language: 'Bahasa Seram & Melayu Maluku',
    coordinates: { lat: -2.992, lng: 129.136 }
  },
  {
    id: '22',
    name: 'Pulau Seribu',
    location: 'DKI Jakarta',
    description: 'Gugusan pulau di utara Jakarta dengan pantai pasir putih and spot snorkeling yang asri.',
    price: 2000000,
    distance: 0,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?q=80&w=1932&auto=format&fit=crop',
    tags: ['Pantai', 'Bahari', 'Snorkeling'],
    matchScore: 86,
    facilities: ['Speedboat', 'Resort Pulau', 'Alat Snorkeling'],
    culture: 'Kultur pesisir Betawi yang modern namun tetap menjaga kearifan lokal kelautan.',
    food: ['Soto Betawi', 'Kerak Telor', 'Seafood Panggang'],
    language: 'Bahasa Betawi & Indonesia',
    coordinates: { lat: -5.617, lng: 106.617 }
  },
  {
    id: '21',
    name: 'Bukittinggi',
    location: 'Sumatera Barat',
    description: 'Kota bersejarah dengan Jam Gadang yang ikonik dan pemandangan Ngarai Sianok yang dramatis.',
    price: 3500000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1516690553959-71a414d6b9b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Sejarah', 'Kuliner', 'Alam'],
    matchScore: 88,
    facilities: ['Hotel', 'Pasar Tradisional', 'Pemandu'],
    culture: 'Adat Minangkabau yang kental dengan filosofi Alam Takambang Jadi Guru.',
    food: ['Rendang', 'Nasi Kapau', 'Itiak Lado Mudo'],
    language: 'Bahasa Minang',
    coordinates: { lat: -0.305, lng: 100.369 }
  },
  {
    id: '23',
    name: 'Pulau Weh',
    location: 'Sabang, Aceh',
    description: 'Titik nol kilometer Indonesia dengan keindahan bawah laut yang jernih dan tenang.',
    price: 6500000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1544526226-d4568090ffb8?q=80&w=2070&auto=format&fit=crop',
    tags: ['Bahari', 'Snorkeling', 'Relaksasi'],
    matchScore: 85,
    facilities: ['Diving Center', 'Bungalow', 'Sewa Motor'],
    culture: 'Penerapan syariat Islam yang harmonis dengan keterbukaan masyarakat pesisir.',
    food: ['Mie Aceh', 'Sate Gurita', 'Kopi Gayo'],
    language: 'Bahasa Aceh',
    coordinates: { lat: 5.823, lng: 95.316 }
  },
  {
    id: '24',
    name: 'Ubud',
    location: 'Gianyar, Bali',
    description: 'Pusat seni dan budaya Bali yang dikelilingi hutan hujan dan terasering sawah yang hijau.',
    price: 5500000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=2076&auto=format&fit=crop',
    tags: ['Seni', 'Budaya', 'Yoga'],
    matchScore: 92,
    facilities: ['Resort Mewah', 'Galeri Seni', 'Pusat Yoga'],
    culture: 'Kehidupan komunal Banjar dan tradisi spiritual yang menyatu dalam kesenian.',
    food: ['Bebek Betutu', 'Nasi Campur Ubud', 'Sate Lilit'],
    language: 'Bahasa Bali',
    coordinates: { lat: -8.506, lng: 115.262 }
  },
  {
    id: '25',
    name: 'Mandalika',
    location: 'Lombok Tengah, NTB',
    description: 'Kawasan ekonomi khusus pariwisata dengan sirkuit balap internasional dan pantai yang memesona.',
    price: 7000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=2070&auto=format&fit=crop',
    tags: ['Sport', 'Pantai', 'Modern'],
    matchScore: 89,
    facilities: ['Sirkuit', 'Hotel Bintang 5', 'Beach Club'],
    culture: 'Tradisi Bau Nyale, ritual menangkap cacing laut yang dipercaya sebagai jelmaan putri.',
    food: ['Ayam Taliwang', 'Nasi Balap', 'Bebereq Terong'],
    language: 'Bahasa Sasak',
    coordinates: { lat: -8.895, lng: 116.295 }
  },
  {
    id: '26',
    name: 'Waerebo',
    location: 'Manggarai, NTT',
    description: 'Desa adat di atas awan yang terpencil dengan rumah kerucut Mbaru Niang yang unik.',
    price: 4500000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1516690553959-71a414d6b9b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Budaya', 'Hiking', 'Terpencil'],
    matchScore: 94,
    facilities: ['Homestay Adat', 'Pemandu', 'Makan Lokal'],
    culture: 'Sistem adat yang masih murni di bawah pimpinan tetua suku di pegunungan terisolasi.',
    food: ['Kopi Manggarai', 'Nasi Merah', 'Ayam Kampung'],
    language: 'Bahasa Manggarai',
    coordinates: { lat: -8.653, lng: 120.473 }
  },
  {
    id: '27',
    name: 'Banda Neira',
    location: 'Maluku',
    description: 'Kepulauan penghasil rempah bersejarah dengan benteng kolonial dan gunung api ikonik.',
    price: 8500000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-8034dbca4841?q=80&w=2070&auto=format&fit=crop',
    tags: ['Sejarah', 'Bahari', 'Eksotis'],
    matchScore: 91,
    facilities: ['Penginapan Sejarah', 'Kapal Wisata', 'Museum'],
    culture: 'Kultur campuran Arab, India, Cina, dan Eropa akibat jalur rempah masa lampau.',
    food: ['Ikan Kuah Pala', 'Manisan Pala', 'Papeda'],
    language: 'Bahasa Melayu Banda',
    coordinates: { lat: -4.526, lng: 129.904 }
  },
  {
    id: '28',
    name: 'Taman Nasional Baluran',
    location: 'Situbondo, Jawa Timur',
    description: 'Afrika di Jawa (Little Africa in Java) dengan padang savana luas dan satwa liar.',
    price: 2500000,
    distance: 0,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1602154663343-89fe00095811?q=80&w=2070&auto=format&fit=crop',
    tags: ['Safari', 'Alam', 'Fotografi'],
    matchScore: 84,
    facilities: ['Menara Pandang', 'Kantor TN', 'Penginapan'],
    culture: 'Konservasi alam yang berpadu dengan kearifan lokal masyarakat pesisir Timur Jawa.',
    food: ['Nasi Tempong', 'Pecel Madura', 'Rujak Soto'],
    language: 'Bahasa Madura & Jawa',
    coordinates: { lat: -7.838, lng: 114.453 }
  },
  {
    id: '29',
    name: 'Pahawang',
    location: 'Pesawaran, Lampung',
    description: 'Pulau dengan taman laut yang indah untuk snorkeling dan jembatan pasir natural.',
    price: 2000000,
    distance: 0,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1544526226-d4568090ffb8?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Snorkeling', 'Murah'],
    matchScore: 82,
    facilities: ['Homestay', 'Sewa Alat Selam', 'Warung'],
    culture: 'Masyarakat pesisir Lampung yang ramah dengan tradisi nelayan yang kuat.',
    food: ['Seruit', 'Pindang Patin', 'Kopi Lampung'],
    language: 'Bahasa Lampung & Jawa',
    coordinates: { lat: -5.673, lng: 105.218 }
  },
  {
    id: '30',
    name: 'Pantai Klayar',
    location: 'Pacitan, Jawa Timur',
    description: 'Pantai dengan fenomena seruling samudra dan formasi batu karang mirip Sphinx.',
    price: 1500000,
    distance: 0,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-8034dbca4841?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Geologi', 'Alam'],
    matchScore: 83,
    facilities: ['Parkir Luas', 'Warung Makan', 'Panggung Pandang'],
    culture: 'Budaya Jawa pesisir Selatan yang masih menjunjung tinggi mitos laut Kidul.',
    food: ['Sego Tiwul', 'Ikan Bakar', 'Otak-otak'],
    language: 'Bahasa Jawa',
    coordinates: { lat: -8.225, lng: 111.018 }
  },
  {
    id: '31',
    name: 'Ngarai Sianok',
    location: 'Bukittinggi, Sumatera Barat',
    description: 'Lembah curam yang dikelilingi oleh pemandangan perbukitan hijau dan sungai berkelok.',
    price: 2500000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1516690553959-71a414d6b9b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Alam', 'Hiking', 'Fotografi'],
    matchScore: 87,
    facilities: ['Parkir', 'Toko Suvenir', 'Toilet'],
    culture: 'Masyarakat lokal yang menjaga kelestarian lembah sebagai paru-paru kota.',
    food: ['Gulai Itiak', 'Kopi Bukittinggi', 'Sanjai'],
    language: 'Bahasa Minang',
    coordinates: { lat: -0.306, lng: 100.364 }
  },
  {
    id: '32',
    name: 'Tanjung Lesung',
    location: 'Pandeglang, Banten',
    description: 'Kawasan ekonomi khusus dengan pantai pasir putih dan budaya Baduy yang menginspirasi.',
    price: 5000000,
    distance: 0,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1544526226-d4568090ffb8?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Budaya', 'Keluarga'],
    matchScore: 81,
    facilities: ['Beach Club', 'Water Sport', 'Resort'],
    culture: 'Kedekatan dengan suku Baduy yang masih memegang teguh larangan adat leluhur.',
    food: ['Otak-otak Labuan', 'Rabeg', 'Sate Bandeng'],
    language: 'Bahasa Sunda & Banten',
    coordinates: { lat: -6.478, lng: 105.658 }
  },
  {
    id: '33',
    name: 'Nihi Sumba',
    location: 'Sumba Barat, NTT',
    description: 'Salah satu hotel terbaik di dunia dengan keindahan ombak dan kultur kuda Sumba.',
    price: 25000000,
    distance: 0,
    rating: 5.0,
    imageUrl: 'https://images.unsplash.com/photo-1516690553959-71a414d6b9b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Mewah', 'Selancar', 'Eksotis'],
    matchScore: 96,
    facilities: ['Resort Private', 'Kuda Nil', 'Spa'],
    culture: 'Kepercayaan Marapu yang tercermin dalam makam batu megalitik dan rumah adat beratap tinggi.',
    food: ['Bolu Sumba', 'Daging Asap', 'Kopi Sumba'],
    language: 'Bahasa Sumba',
    coordinates: { lat: -9.756, lng: 119.345 }
  },
  {
    id: '34',
    name: 'Lembah Baliem',
    location: 'Wamena, Papua Pegunungan',
    description: 'Lembah di jantung pegunungan Jayawijaya dengan tradisi perang suku tahunan yang megah.',
    price: 18000000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1516690553959-71a414d6b9b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Budaya', 'Antropologi', 'Petualangan'],
    matchScore: 93,
    facilities: ['Pemandu Lokal', 'Homestay', 'Transport Udara'],
    culture: 'Kultur suku Dani, Yali, dan Lani yang masih menjaga tradisi bakar batu dan koteka.',
    food: ['Udang Selingkuh', 'Sagu Bakar', 'Ubi'],
    language: 'Bahasa Dani',
    coordinates: { lat: -4.095, lng: 138.945 }
  },
  {
    id: '35',
    name: 'Danau Sentani',
    location: 'Jayapura, Papua',
    description: 'Danau luas di bawah kaki pegunungan Cyclops dengan pulau-pulau kecil di tengahnya.',
    price: 6000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1516690553959-71a414d6b9b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Danau', 'Edukasi', 'Alam'],
    matchScore: 86,
    facilities: ['Perahu Wisata', 'Hotel', 'Restoran'],
    culture: 'Seni lukis kulit kayu Asei yang menceritakan kehidupan masyarakat danau.',
    food: ['Ikan Gabus Sentani', 'Papeda Bungkus', 'Sayur Paku'],
    language: 'Bahasa Sentani',
    coordinates: { lat: -2.595, lng: 140.495 }
  },
  {
    id: '36',
    name: 'Maratua',
    location: 'Berau, Kalimantan Timur',
    description: 'Maladewa-nya Kalimantan Timur dengan resort di atas air dan penyu yang berseliweran.',
    price: 13000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1544526226-d4568090ffb8?q=80&w=2070&auto=format&fit=crop',
    tags: ['Honeymoon', 'Diving', 'Mewah'],
    matchScore: 90,
    facilities: ['Water Villa', 'Sewa Alat Selam', 'Wi-Fi'],
    culture: 'Masyarakat suku Bajau yang bermukim di pesisir dengan gaya hidup maritim yang kuat.',
    food: ['Ikan Bakar', 'Tapa-tapa', 'Sagu'],
    language: 'Bahasa Bajau',
    coordinates: { lat: 2.215, lng: 118.575 }
  },
  {
    id: '37',
    name: 'Pasar Terapung Lok Baintan',
    location: 'Banjar, Kalimantan Selatan',
    description: 'Pasar tradisional di atas sungai Barito yang masih menggunakan sistem barter.',
    price: 3000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1544526226-d4568090ffb8?q=80&w=2070&auto=format&fit=crop',
    tags: ['Budaya', 'Sungai', 'Kuliner'],
    matchScore: 85,
    facilities: ['Sewa Kelotok', 'Warung Terapung', 'Pemandu'],
    culture: 'Budaya sungai suku Banjar yang telah mendarah daging selama ratusan tahun.',
    food: ['Soto Banjar', 'Ketupat Kandangan', 'Bingka'],
    language: 'Bahasa Banjar',
    coordinates: { lat: -3.315, lng: 114.675 }
  },
  {
    id: '38',
    name: 'Takabonerate',
    location: 'Kepulauan Selayar, Sulsel',
    description: 'Kawasan atol terbesar ketiga di dunia dengan ratusan titik selam yang fantastis.',
    price: 9000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-8034dbca4841?q=80&w=2070&auto=format&fit=crop',
    tags: ['Diving', 'Atol', 'Terpencil'],
    matchScore: 89,
    facilities: ['Dive Center', 'Transportasi Laut', 'Akomodasi'],
    culture: 'Masyarakat Bugis-Makassar yang ahli dalam pelayaran dan pengetahuan kelautan.',
    food: ['Coto Makassar', 'Ikan Terbang Bakar', 'Konro'],
    language: 'Bahasa Makassar & Bajo',
    coordinates: { lat: -6.685, lng: 121.165 }
  },
  {
    id: '39',
    name: 'Pantai Losari',
    location: 'Makassar, Sulawesi Selatan',
    description: 'Ikon kota Makassar yang populer untuk menikmati pemandangan matahari terbenam.',
    price: 1000000,
    distance: 0,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-8034dbca4841?q=80&w=2070&auto=format&fit=crop',
    tags: ['Kota', 'Sunset', 'Kuliner'],
    matchScore: 82,
    facilities: ['Area Pejalan Kaki', 'Masjid Terapung', 'Wisata Kuliner'],
    culture: 'Kota pelabuhan kosmopolitan yang bangga akan sejarah maritimnya.',
    food: ['Pisang Epe', 'Pallubasa', 'Es Pisang Ijo'],
    language: 'Bahasa Makassar',
    coordinates: { lat: -5.145, lng: 119.405 }
  },
  {
    id: '40',
    name: 'Likupang',
    location: 'Minahasa Utara, Sulawesi Utara',
    description: 'Destinasi wisata super prioritas dengan pantai pasir putih dan padang savana hijau.',
    price: 8000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-8034dbca4841?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Savana', 'Modern'],
    matchScore: 87,
    facilities: ['Resort Mewah', 'Akses Jalan Mulus', 'Restoran'],
    culture: 'Kultur Minahasa yang toleran dengan keramahan penduduk yang religius.',
    food: ['Gohu', 'Lalampa', 'Panada'],
    language: 'Bahasa Manado',
    coordinates: { lat: 1.675, lng: 125.075 }
  },
  {
    id: '41',
    name: 'Morotai',
    location: 'Maluku Utara',
    description: 'Pulau di garis depan yang kaya akan sisa-sisa sejarah Perang Dunia II di bawah laut.',
    price: 10000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-8034dbca4841?q=80&w=2070&auto=format&fit=crop',
    tags: ['Sejarah', 'Diving', 'Terpencil'],
    matchScore: 88,
    facilities: ['Museum Perang', 'Bandara', 'Dive Center'],
    culture: 'Keunikan sejarah pertahanan militer Pasifik yang berpadu dengan kearifan lokal.',
    food: ['Gohu Ikan', 'Nasi Lapola', 'Popeda'],
    language: 'Bahasa Morotai & Melayu',
    coordinates: { lat: 2.325, lng: 128.435 }
  },
  {
    id: '42',
    name: 'Kepulauan Natuna',
    location: 'Kepulauan Riau',
    description: 'Gerbang utara Indonesia dengan pemandangan batu-batu granit raksasa di tepi laut.',
    price: 11000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1544526226-d4568090ffb8?q=80&w=2070&auto=format&fit=crop',
    tags: ['Eksotis', 'Geopark', 'Damai'],
    matchScore: 85,
    facilities: ['Parkir', 'Pemandu', 'Restoran Seafood'],
    culture: 'Masyarakat Melayu Natuna yang sangat dekat dengan adat Melayu Serumpun.',
    food: ['Kernas', 'Lakse', 'Pedas'],
    language: 'Bahasa Melayu Natuna',
    coordinates: { lat: 3.945, lng: 108.385 }
  },
  {
    id: '43',
    name: 'Lawang Sewu',
    location: 'Semarang, Jawa Tengah',
    description: 'Bangunan kolonial bersejarah dengan seribu pintu yang megah dan misterius.',
    price: 1500000,
    distance: 0,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?q=80&w=2071&auto=format&fit=crop',
    tags: ['Sejarah', 'Arsitektur', 'Urban'],
    matchScore: 84,
    facilities: ['Museum', 'Pemandu', 'Area Parkir'],
    culture: 'Peninggalan sejarah perkeretaapian Hindia Belanda yang legendaris di tanah Jawa.',
    food: ['Lumpia Semarang', 'Tahu Gimbal', 'Bandeng Presto'],
    language: 'Bahasa Jawa & Indonesia',
    coordinates: { lat: -6.984, lng: 110.410 }
  },
  {
    id: '44',
    name: 'Keraton Surakarta',
    location: 'Solo, Jawa Tengah',
    description: 'Pusat kebudayaan Jawa yang autentik dengan kemegahan istana kerajaan Mataram Islam.',
    price: 2000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?q=80&w=2071&auto=format&fit=crop',
    tags: ['Budaya', 'Keraton', 'Edukasi'],
    matchScore: 90,
    facilities: ['Museum', 'Pemandu Keraton', 'Pertunjukan Tari'],
    culture: 'Tradisi luhur Jawa dengan etika (unggah-ungguh) yang tetap dijaga ketat di lingkungan istana.',
    food: ['Nasi Liwet', 'Selat Solo', 'Serabi Solo'],
    language: 'Bahasa Jawa Krama',
    coordinates: { lat: -7.577, lng: 110.829 }
  },
  {
    id: '45',
    name: 'Tebing Breksi',
    location: 'Sleman, Yogyakarta',
    description: 'Bekas tambang batu yang disulap menjadi destinasi wisata dengan ukiran seni raksasa.',
    price: 1000000,
    distance: 0,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?q=80&w=2071&auto=format&fit=crop',
    tags: ['Seni', 'Fotografi', 'Geologi'],
    matchScore: 83,
    facilities: ['Amfiteater', 'Jeep Tour', 'Food Court'],
    culture: 'Kreativitas masyarakat lokal dalam mengubah ancaman lingkungan menjadi aset produktif.',
    food: ['Gudeg', 'Bakpia', 'Geplak'],
    language: 'Bahasa Jawa',
    coordinates: { lat: -7.781, lng: 110.484 }
  },
  {
    id: '46',
    name: 'Pantai Kuta',
    location: 'Badung, Bali',
    description: 'Destinasi wisata paling ikonik di Bali yang legendaris dengan pasir putih dan matahari terbenam.',
    price: 1500000,
    distance: 0,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=2076&auto=format&fit=crop',
    tags: ['Pantai', 'Hiburan', 'Ikonik'],
    matchScore: 82,
    facilities: ['Pusat Perbelanjaan', 'Bar', 'Sewa Papan Selancar'],
    culture: 'Hub pariwisata global yang mempertemukan berbagai kebudayaan dunia di satu garis pantai.',
    food: ['Nasi Jinggo', 'Smoothie Bowl', 'Seafood'],
    language: 'Bahasa Bali & Inggris',
    coordinates: { lat: -8.717, lng: 115.174 }
  },
  {
    id: '47',
    name: 'Batu Karas',
    location: 'Pangandaran, Jawa Barat',
    description: 'Titik favorit bagi peselancar pemula dengan ombak yang bersahabat dan suasana santai.',
    price: 3000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1544526226-d4568090ffb8?q=80&w=2070&auto=format&fit=crop',
    tags: ['Selancar', 'Pantai', 'Sunda'],
    matchScore: 86,
    facilities: ['Sewa Papan', 'Kafe Tepi Pantai', 'Homestay'],
    culture: 'Ramah tamah khas masyarakat Sunda pesisir yang menjunjung tinggi toleransi.',
    food: ['Nasi Liwet', 'Pindang Gunung', 'Jus Honje'],
    language: 'Bahasa Sunda',
    coordinates: { lat: -7.711, lng: 108.455 }
  },
  {
    id: '48',
    name: 'Pantai Kolbano',
    location: 'Timor Tengah Selatan, NTT',
    description: 'Pantai unik dengan bebatuan berwarna-warni dan air yang sangat biru di selatan pulau Timor.',
    price: 5500000,
    distance: 0,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1516690553959-71a414d6b9b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Eksotis', 'Fotografi', 'Terpencil'],
    matchScore: 84,
    facilities: ['Minimalis', 'Parkir', 'Warung Lokal'],
    culture: 'Kultur masyarakat Timor yang kental dengan persaudaraan dan tradisi tenun ikat.',
    food: ['Seafood NTT', 'Daging Se’i', 'Jagung Bose'],
    language: 'Bahasa Dawan & Indonesia',
    coordinates: { lat: -9.985, lng: 124.495 }
  },
  {
    id: '49',
    name: 'Kakaban',
    location: 'Berau, Kalimantan Timur',
    description: 'Danau air payau dengan populasi ubur-ubur tanpa sengat yang eksklusif di dunia.',
    price: 8000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?q=80&w=1974&auto=format&fit=crop',
    tags: ['Bahari', 'Langka', 'Snorkeling'],
    matchScore: 91,
    facilities: ['Jalan Kayu', 'Alat Snorkeling', 'Pemandu'],
    culture: 'Penjagaan ekosistem yang sangat ketat oleh otoritas lokal demi kelestarian alam langka.',
    food: ['Kepiting Kenari', 'Ikan Bakar', 'Elai'],
    language: 'Bahasa Berau',
    coordinates: { lat: 2.155, lng: 118.525 }
  },
  {
    id: '50',
    name: 'Sangalaki',
    location: 'Berau, Kalimantan Timur',
    description: 'Habitat penting bagi pari manta raksasa dan penyu hijau untuk bertelur.',
    price: 9000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?q=80&w=1974&auto=format&fit=crop',
    tags: ['Manta', 'Penyu', 'Konservasi'],
    matchScore: 89,
    facilities: ['Pos Konservasi', 'Diving Center', 'Resort Ekologi'],
    culture: 'Komitmen kuat masyarakat dalam melindungi satwa laut yang terancam punah.',
    food: ['Seafood Lokal', 'Kopi', 'Buah Buahan'],
    language: 'Bahasa Indonesia',
    coordinates: { lat: 2.185, lng: 118.425 }
  },
  {
    id: '51',
    name: 'Kepulauan Mentawai',
    location: 'Sumatera Barat',
    description: 'Surga bagi peselancar dunia dengan ombak legendaris dan budaya suku pedalaman yang unik.',
    price: 15000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1516690553959-71a414d6b9b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Selancar', 'Budaya', 'Eksotis'],
    matchScore: 92,
    facilities: ['Surf Camp', 'Pemandu Adat', 'Kapal Charter'],
    culture: 'Tradisi tato Mentawai yang merupakan salah satu seni rajah tertua di dunia dan kehidupan suku Sikerey.',
    food: ['Sagu Mentawai', 'Ikan Bakar Bambu', 'Subbet'],
    language: 'Bahasa Mentawai',
    coordinates: { lat: -1.397, lng: 98.924 }
  },
  {
    id: '52',
    name: 'Candi Prambanan',
    location: 'Sleman, Yogyakarta',
    description: 'Kompleks candi Hindu terbesar di Indonesia yang megah dengan relief cerita Ramayana.',
    price: 3000000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1603566113110-66029302ca5d?q=80&w=2070&auto=format&fit=crop',
    tags: ['Sejarah', 'Budaya', 'Ikonik'],
    matchScore: 95,
    facilities: ['Museum', 'Sendratari Ramayana', 'Taman Luas'],
    culture: 'Arsitektur Hindu kuno yang megah dan pertunjukan seni tari kolosal yang mendunia.',
    food: ['Gudeg', 'Bakmi Jawa', 'Wedang Ronde'],
    language: 'Bahasa Jawa',
    coordinates: { lat: -7.752, lng: 110.491 }
  }
];
