import { Destination } from './types';

export const DESTINATIONS: Destination[] = [
  {
    id: '1',
    name: 'Candi Borobudur',
    location: 'Magelang, Jawa Tengah',
    description: 'Candi Budha terbesar di dunia, sebuah mahakarya arsitektur kuno yang menakjubkan.',
    price: 3500000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?q=80&w=2071&auto=format&fit=crop',
    tags: ['Budaya', 'Sejarah', 'Edukasi'],
    matchScore: 95,
    facilities: ['Wi-Fi', 'Pemandu Wisata', 'Area Parkir', 'Toilet'],
    culture: 'Warisan Budaya Buddha tertua di dunia dengan arsitektur Javanese-Buddhist yang megah.',
    food: ['Gudeg Magelang', 'Bakpia Pathok', 'Sego Megono'],
    language: 'Bahasa Jawa & Indonesia',
    coordinates: { lat: -7.607, lng: 110.203 }
  },
  {
    id: '2',
    name: 'Raja Ampat',
    location: 'Papua Barat',
    description: 'Surga bawah laut dengan keanekaragaman hayati laut tertinggi di dunia.',
    price: 15000000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1516690553959-71a414d6b9b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Bahari', 'Petualangan', 'Eksotis'],
    matchScore: 92,
    facilities: ['Diving Center', 'Resort', 'Perahu Wisata'],
    culture: 'Kesenian ukir kayu suku Asmat dan musik petikan tradisional Papua yang khas.',
    food: ['Papeda', 'Ikan Kuah Kuning', 'Sagu Sep'],
    language: 'Bahasa Papua & Indonesia',
    coordinates: { lat: -0.231, lng: 130.518 }
  },
  {
    id: '3',
    name: 'Taman Nasional Komodo',
    location: 'NTT',
    description: 'Rumah bagi kadal purba Komodo dan pemandangan pulau Padar yang spektakuler.',
    price: 8500000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=2070&auto=format&fit=crop',
    tags: ['Alam', 'Satwa', 'Hiking'],
    matchScore: 90,
    facilities: ['Pemandu Wisata', 'Kantin', 'Toilet'],
    culture: 'Kultur masyarakat pesisir Manggarai yang hidup berdampingan dengan alam liar.',
    food: ['Seafood Bakar', 'Kopi Flores', 'Jagung Bose'],
    language: 'Bahasa Manggarai & NTT',
    coordinates: { lat: -8.583, lng: 119.5 }
  },
  {
    id: '4',
    name: 'Gunung Bromo',
    location: 'Probolinggo, Jawa Timur',
    description: 'Pemandangan matahari terbit yang ikonik dengan latar belakang kawah Bromo yang mengepul.',
    price: 2500000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1602641021461-12503957eb6a?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pegunungan', 'Fotografi', 'Petualangan'],
    matchScore: 88,
    facilities: ['Jeep Sewa', 'Kuda', 'Toilet', 'Warung Makan'],
    culture: 'Upacara Kasada dari Suku Tengger yang memuja Dewa di kawah Bromo.',
    food: ['Bakso Malang', 'Nasi Campur Bromo', 'Jagung Bakar'],
    language: 'Bahasa Jawa Tengger',
    coordinates: { lat: -7.942, lng: 112.953 }
  },
  {
    id: '5',
    name: 'Danau Toba',
    location: 'Parapat, Sumatera Utara',
    description: 'Danau vulkanik terbesar di dunia dengan keindahan Pulau Samosir di tengahnya.',
    price: 4000000,
    distance: 0,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1544526226-d4568090ffb8?q=80&w=2070&auto=format&fit=crop',
    tags: ['Danau', 'Budaya', 'Keluarga'],
    matchScore: 85,
    facilities: ['Kapal Wisata', 'Hotel', 'Restoran'],
    culture: 'Rumah adat Bolon dan pertunjukan boneka Sigale-gale khas suku Batak Toba.',
    food: ['Arsik Ikan Mas', 'Mie Gomak', 'Dali ni Horbo'],
    language: 'Bahasa Batak Toba',
    coordinates: { lat: 2.684, lng: 98.847 }
  },
  {
    id: '6',
    name: 'Tanah Lot',
    location: 'Tabanan, Bali',
    description: 'Pura yang terletak di atas batu karang besar di pinggir laut, sangat indah saat matahari terbenam.',
    price: 3000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=2076&auto=format&fit=crop',
    tags: ['Pura', 'Pantai', 'Religi'],
    matchScore: 87,
    facilities: ['Area Parkir', 'Toko Suvenir', 'Toilet'],
    culture: 'Tradisi Odalan dan ritual sembahyang harian umat Hindu Bali di tepi samudra.',
    food: ['Ayam Betutu', 'Sate Lilit', 'Babi Guling'],
    language: 'Bahasa Bali & Indonesia',
    coordinates: { lat: -8.621, lng: 115.086 }
  },
  {
    id: '7',
    name: 'Wakatobi',
    location: 'Sulawesi Tenggara',
    description: 'Destinasi diving kelas dunia dengan terumbu karang yang masih sangat alami.',
    price: 12000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=2070&auto=format&fit=crop',
    tags: ['Bahari', 'Diving', 'Relaksasi'],
    matchScore: 84,
    facilities: ['Diving Boat', 'Resort', 'Wi-Fi'],
    culture: 'Kehidupan suku Bajo, para pengembara laut yang legendaris di Nusantara.',
    food: ['Kasami', 'Sinonggi', 'Lapa-lapa'],
    language: 'Bahasa Wakatobi & Bajo',
    coordinates: { lat: -5.603, lng: 123.63 }
  },
  {
    id: '8',
    name: 'Labuan Bajo',
    location: 'Manggarai Barat, NTT',
    description: 'Gerbang utama menuju Pulau Komodo dengan pelabuhan yang sangat menawan.',
    price: 9000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Sailing', 'Gourmet'],
    matchScore: 89,
    facilities: ['Kapal Phinisi', 'Bandara Internasional', 'Hotel Mewah'],
    culture: 'Perpaduan budaya maritim dan pegunungan Manggarai di Barat Flores.',
    food: ['Seafood Platter', 'Kopi Juria', 'Ikan Cara'],
    language: 'Bahasa Manggarai',
    coordinates: { lat: -8.490, lng: 119.880 }
  },
  {
    id: '9',
    name: 'Kepulauan Derawan',
    location: 'Berau, Kalimantan Timur',
    description: 'Berhenti untuk melihat penyu bertelur dan berenang bersama ubur-ubur tanpa sengat.',
    price: 7000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?q=80&w=1974&auto=format&fit=crop',
    tags: ['Penyu', 'Bahari', 'Ubur-ubur'],
    matchScore: 83,
    facilities: ['Homestay', 'Alat Snorkeling', 'Pemandu Lokal'],
    culture: 'Kultur pesisir Kalimantan yang sangat bergantung pada kelestarian penyu.',
    food: ['Tehe-tehe', 'Elai', 'Seafood Segar'],
    language: 'Bahasa Melayu Berau',
    coordinates: { lat: 2.285, lng: 118.238 }
  },
  {
    id: '10',
    name: 'Bunaken',
    location: 'Manado, Sulawesi Utara',
    description: 'Taman laut yang terkenal dengan dinding karang (wall diving) yang spektakuler.',
    price: 6000000,
    distance: 0,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1629236467006-25807490076c?q=80&w=2070&auto=format&fit=crop',
    tags: ['Bahari', 'Snorkeling', 'Wall Diving'],
    matchScore: 81,
    facilities: ['Sewa Alat Selam', 'Transportasi Perahu', 'Warung Makan'],
    culture: 'Kultur Minahasa yang kaya akan sejarah perdagangan rempah dan musik Kolintang.',
    food: ['Bubur Manado', 'Cakalang Fufu', 'Klappertaart'],
    language: 'Bahasa Manado',
    coordinates: { lat: 1.616, lng: 124.757 }
  },
  {
    id: '11',
    name: 'Nusa Penida',
    location: 'Klungkung, Bali',
    description: 'Pulau eksotis dengan tebing ikonik Kelingking Beach dan air laut yang biru kristal.',
    price: 4500000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Tebing', 'Instagenic'],
    matchScore: 94,
    facilities: ['Penyewaan Motor', 'Tour Lokal', 'Restoran'],
    culture: 'Tradisi spiritual Bali yang sangat kuat dengan banyak pura suci di dinding tebing.',
    food: ['Ikan Bakar', 'Tipat Cantok', 'Sate Renteng'],
    language: 'Bahasa Bali Alus',
    coordinates: { lat: -8.728, lng: 115.544 }
  },
  {
    id: '12',
    name: 'Gili Trawangan',
    location: 'Lombok, NTB',
    description: 'Pulau bebas kendaraan bermotor dengan suasana pesta yang hidup dan snorkeling yang indah.',
    price: 5500000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1534008757030-27299c4371b6?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Nightlife', 'Snorkeling'],
    matchScore: 91,
    facilities: ['Sewa Sepeda', 'Cidomo', 'Bar Tepi Pantai'],
    culture: 'Perpaduan budaya Sasak lokal dengan komunitas traveler global yang santai.',
    food: ['Ayam Taliwang', 'Plecing Kangkung', 'Sate Rembiga'],
    language: 'Bahasa Sasak & Inggris',
    coordinates: { lat: -8.351, lng: 116.039 }
  },
  {
    id: '13',
    name: 'Gunung Rinjani',
    location: 'Lombok, NTB',
    description: 'Gunung berapi tertinggi kedua di Indonesia dengan Danau Segara Anak yang memukau.',
    price: 6500000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1554486855-33ec7c81604a?q=80&w=2070&auto=format&fit=crop',
    tags: ['Mendaki', 'Alam', 'Danau'],
    matchScore: 88,
    facilities: ['Pemandu Gunung', 'Camping Gear', 'Porter'],
    culture: 'Mitos Dewi Anjani yang sakral bagi masyarakat Lombok dan pendaki.',
    food: ['Ayam Taliwang', 'Sate Bulayak', 'Nasi Balap Puyung'],
    language: 'Bahasa Sasak',
    coordinates: { lat: -8.411, lng: 116.457 }
  },
  {
    id: '14',
    name: 'Dataran Tinggi Dieng',
    location: 'Wonosobo, Jawa Tengah',
    description: 'Negeri di atas awan dengan keindahan candi kuno, kawah belerang, dan Danau Warna.',
    price: 3000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1627914022830-745a3375b47a?q=80&w=2070&auto=format&fit=crop',
    tags: ['Budaya', 'Dingin', 'Alam'],
    matchScore: 86,
    facilities: ['Homestay', 'Area Parkir', 'Warung Kopi'],
    culture: 'Fenomena bocah rambut gimbal dan upacara pemotongan rambut di Dieng Culture Festival.',
    food: ['Mie Ongklok', 'Carica', 'Kripik Jamur'],
    language: 'Bahasa Jawa Ngoko',
    coordinates: { lat: -7.218, lng: 109.916 }
  },
  {
    id: '15',
    name: 'Pulau Belitung',
    location: 'Bangka Belitung',
    description: 'Pantai dengan formasi batu granit raksasa yang artistik dan air yang sangat jernih.',
    price: 5000000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?q=80&w=2070&auto=format&fit=crop',
    tags: ['Pantai', 'Geopark', 'Fotografi'],
    matchScore: 89,
    facilities: ['Sewa Perahu', 'Hotel', 'Seafood'],
    culture: 'Budaya literasi Laskar Pelangi dan sejarah tambang timah yang bersejarah.',
    food: ['Mie Belitung', 'Kopi Joss', 'Gangan Ikan'],
    language: 'Bahasa Melayu Belitung',
    coordinates: { lat: -2.741, lng: 107.618 }
  },
  {
    id: '16',
    name: 'Tana Toraja',
    location: 'Toraja, Sulawesi Selatan',
    description: 'Warisan budaya unik dengan rumah adat Tongkonan dan tradisi pemakaman tebing.',
    price: 7000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=2094&auto=format&fit=crop',
    tags: ['Budaya', 'Sejarah', 'Antropologi'],
    matchScore: 84,
    facilities: ['Pemandu Adat', 'Hotel Lokal', 'Transportasi'],
    culture: 'Ritual Rambu Solo, perayaan kematian paling spektakuler di dunia dengan pengorbanan kerbau.',
    food: ['Pa\'piong', 'Kopi Toraja', 'Jammala'],
    language: 'Bahasa Toraja',
    coordinates: { lat: -2.981, lng: 119.897 }
  },
  {
    id: '17',
    name: 'Tanjung Puting',
    location: 'Kotawaringin Barat, Kalimantan Tengah',
    description: 'Pusat rehabilitasi orangutan di ekosistem hutan hujan tropis yang asri.',
    price: 9500000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1518384400537-88f61a15320d?q=80&w=2070&auto=format&fit=crop',
    tags: ['Satwa', 'Sungai', 'Edukasi'],
    matchScore: 87,
    facilities: ['Kapal Klotok', 'Koki Kapal', 'Pemandu Liar'],
    culture: 'Budaya sungai suku Dayak dan konservasi orangutan di jantung Kalimantan.',
    food: ['Wadi Ikan', 'Juhu Singkah', 'Soto Banjar'],
    language: 'Bahasa Dayak & Banjar',
    coordinates: { lat: -2.859, lng: 111.902 }
  },
  {
    id: '18',
    name: 'Kepulauan Karimunjawa',
    location: 'Jepara, Jawa Tengah',
    description: 'Gugusan pulau dengan penangkaran hiu dan spot snorkeling terumbu karang yang cantik.',
    price: 4000000,
    distance: 0,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=2076&auto=format&fit=crop',
    tags: ['Bahari', 'Relaksasi', 'Hiu'],
    matchScore: 85,
    facilities: ['Ferry Cepat', 'Homestay', 'Alat Snorkeling'],
    culture: 'Kultur masyarakat nelayan Jawa yang damai dengan tradisi pembuatan kapal kayu.',
    food: ['Pindang Serani', 'Tahu Bakso', 'Ikan Bakar Pesisir'],
    language: 'Bahasa Jawa Pesisir',
    coordinates: { lat: -5.857, lng: 110.439 }
  },
  {
    id: '19',
    name: 'Kawah Ijen',
    location: 'Banyuwangi, Jawa Timur',
    description: 'Fenomena api biru (Blue Fire) yang langka dan kawah asam terbesar di dunia.',
    price: 3500000,
    distance: 0,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1549420546-24e03ce6df97?q=80&w=2073&auto=format&fit=crop',
    tags: ['Gunung', 'Belerang', 'Mendaki'],
    matchScore: 88,
    facilities: ['Masker Gas', 'Ojek Troli', 'Warung'],
    culture: 'Kehidupan keras penambang belerang dan tradisi Gandrung dari suku Osing.',
    food: ['Nasi Tempong', 'Pecel Pitik', 'Rujak Soto'],
    language: 'Bahasa Jawa Osing',
    coordinates: { lat: -8.058, lng: 114.242 }
  },
  {
    id: '20',
    name: 'Pantai Ora',
    location: 'Maluku Tengah',
    description: 'Maladewa-nya Indonesia dengan resort terapung di atas air laut yang bening seperti kaca.',
    price: 11000000,
    distance: 0,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=2070&auto=format&fit=crop',
    tags: ['Eksotis', 'Bulan Madu', 'Bahari'],
    matchScore: 93,
    facilities: ['Resort Terapung', 'Restoran', 'Tour Kano'],
    culture: 'Musik Tifa dan keramahan suku Alifuru di pulau Seram yang eksotis.',
    food: ['Papeda', 'Sagu Kasbi', 'Rujak Natsepa'],
    language: 'Bahasa Seram & Melayu Maluku',
    coordinates: { lat: -2.992, lng: 129.136 }
  },
  {
    id: '22',
    name: 'Pulau Seribu',
    location: 'DKI Jakarta',
    description: 'Gugusan pulau di utara Jakarta dengan pantai pasir putih and spot snorkeling yang asri.',
    price: 2000000,
    distance: 0,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?q=80&w=1932&auto=format&fit=crop',
    tags: ['Pantai', 'Bahari', 'Snorkeling'],
    matchScore: 86,
    facilities: ['Speedboat', 'Resort Pulau', 'Alat Snorkeling'],
    culture: 'Kultur pesisir Betawi yang modern namun tetap menjaga kearifan lokal kelautan.',
    food: ['Soto Betawi', 'Kerak Telor', 'Seafood Panggang'],
    language: 'Bahasa Betawi & Indonesia',
    coordinates: { lat: -5.617, lng: 106.617 }
  }
];
